server:
  port: 8780

springdoc:
  swagger-ui:
    enabled: true #开启springdoc
    path: /index.html

logging:
  config: classpath:logback-spring.xml # 日志配置文件位置
spring:
  config:
    activate:
      on-profile: dev
