server:
  port: 8780

spring:
  profiles:
    active: dev #开发环境


springdoc:
  swagger-ui:
    enabled: true #开启springdoc
    path: /index.html

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  config: classpath:log4j2.xml # 日志配置文件位置
